import Head from 'next/head';
import styles from '../styles/Home.module.css';
import SignIn from './SignIn';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>IssueTrack</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main} id="root">
        <SignIn />
      </main>
    </div>
  )
}
